// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Cyberkruz.Autorest.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// A full model of a Joke to pull out of the API.
    /// </summary>
    public partial class Joke
    {
        /// <summary>
        /// Initializes a new instance of the Joke class.
        /// </summary>
        public Joke()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Joke class.
        /// </summary>
        /// <param name="question">The joke's setup question.</param>
        /// <param name="answer">The punchline of the joke.</param>
        public Joke(string question = default(string), string answer = default(string))
        {
            Question = question;
            Answer = answer;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the joke's setup question.
        /// </summary>
        [JsonProperty(PropertyName = "question")]
        public string Question { get; set; }

        /// <summary>
        /// Gets or sets the punchline of the joke.
        /// </summary>
        [JsonProperty(PropertyName = "answer")]
        public string Answer { get; set; }

    }
}
